import courseRobotics from "@/assets/course-robotics.jpg";
import courseCoding from "@/assets/course-coding.jpg";
import courseChess from "@/assets/course-chess.jpg";
import courseSpeaking from "@/assets/course-speaking.jpg";

export interface Course {
  id: string;
  image: string;
  title: string;
  description: string;
  rating: number;
  learners: string;
  language: string;
  level: string;
  classes: number;
  ageRange: string;
  timeSlot: "Morning" | "Afternoon" | "Evening" | "Late Evening";
  originalPrice: number;
  salePrice: number;
  badge?: string;
  teacher: { name: string; subject: string; rating: number };
  syllabus: string[];
}

export const ALL_COURSES: Course[] = [
  {
    id: "robotics-summer-camp",
    image: courseRobotics,
    title: "Summer robotics camp: fun projects with Arduino, TinkerCAD coding and 3D printing",
    description: "Build circuits & smart projects like alarms, weather stations, etc.",
    rating: 4.9,
    learners: "200+",
    language: "English",
    level: "Intermediate",
    classes: 4,
    ageRange: "7-10 yrs",
    timeSlot: "Morning",
    originalPrice: 499,
    salePrice: 299,
    badge: "Selling Fast",
    teacher: { name: "Andy Brew", subject: "Robotics & STEM", rating: 4.9 },
    syllabus: ["Intro to Arduino", "Sensors", "TinkerCAD", "Mini Project"],
  },
  {
    id: "creative-coding-scratch",
    image: courseCoding,
    title: "Creative coding for kids: build your first game with Scratch",
    description: "Learn programming fundamentals through game-building exercises.",
    rating: 4.8,
    learners: "350+",
    language: "English",
    level: "Beginner",
    classes: 5,
    ageRange: "5-8 yrs",
    timeSlot: "Afternoon",
    originalPrice: 449,
    salePrice: 259,
    badge: "New",
    teacher: { name: "Andy Brew", subject: "Coding & Game Dev", rating: 4.8 },
    syllabus: ["Scratch basics", "Sprites", "Loops", "Events", "Final game"],
  },
  {
    id: "chess-masterclass",
    image: courseChess,
    title: "Chess masterclass: strategy and tactics for young minds",
    description: "Master openings, tactics, and endgame strategy with experts.",
    rating: 4.9,
    learners: "150+",
    language: "English",
    level: "Beginner",
    classes: 6,
    ageRange: "6-12 yrs",
    timeSlot: "Evening",
    originalPrice: 499,
    salePrice: 299,
    teacher: { name: "Andy Brew", subject: "Chess Strategy", rating: 4.7 },
    syllabus: ["Rules", "Opening", "Tactics", "Endgame", "Positional play", "Prep"],
  },
  {
    id: "public-speaking",
    image: courseSpeaking,
    title: "Public speaking & communication skills for confident kids",
    description: "Build confidence and become a strong storyteller and speaker.",
    rating: 4.7,
    learners: "180+",
    language: "English",
    level: "All Levels",
    classes: 4,
    ageRange: "8-14 yrs",
    timeSlot: "Late Evening",
    originalPrice: 399,
    salePrice: 249,
    badge: "Selling Fast",
    teacher: { name: "Andy Brew", subject: "Public Speaking", rating: 4.9 },
    syllabus: ["Voice", "Storytelling", "Body language", "Final speech"],
  },
  {
    id: "advanced-robotics-iot",
    image: courseRobotics,
    title: "Advanced robotics: IoT projects with sensors and motors",
    description: "Create smart home mini-projects with sensors and IoT concepts.",
    rating: 4.9,
    learners: "120+",
    language: "English",
    level: "Advanced",
    classes: 6,
    ageRange: "10-15 yrs",
    timeSlot: "Evening",
    originalPrice: 699,
    salePrice: 399,
    badge: "New",
    teacher: { name: "Andy Brew", subject: "Robotics & STEM", rating: 4.9 },
    syllabus: ["IoT intro", "Sensors", "Motors", "Automation", "Cloud", "Demo"],
  },
  {
    id: "python-for-kids",
    image: courseCoding,
    title: "Python for kids: logic, loops, and mini apps",
    description: "A beginner-friendly path to Python with hands-on mini projects.",
    rating: 4.8,
    learners: "280+",
    language: "English",
    level: "Beginner",
    classes: 5,
    ageRange: "9-14 yrs",
    timeSlot: "Morning",
    originalPrice: 499,
    salePrice: 299,
    badge: "Selling Fast",
    teacher: { name: "Andy Brew", subject: "Programming", rating: 4.8 },
    syllabus: ["Variables", "Conditions", "Loops", "Functions", "Mini app"],
  },
  {
    id: "ai-art-explorer",
    image: courseSpeaking,
    title: "AI art explorer: creativity with prompts and storytelling",
    description: "Combine imagination and technology in fun visual storytelling tasks.",
    rating: 4.6,
    learners: "160+",
    language: "English",
    level: "Intermediate",
    classes: 4,
    ageRange: "8-13 yrs",
    timeSlot: "Afternoon",
    originalPrice: 429,
    salePrice: 239,
    teacher: { name: "Andy Brew", subject: "Creative Tech", rating: 4.7 },
    syllabus: ["Prompt basics", "Styles", "Story scenes", "Portfolio"],
  },
  {
    id: "maths-logic-games",
    image: courseChess,
    title: "Maths and logic games: fast thinking for young minds",
    description: "Build quick reasoning with puzzles, patterns, and brain games.",
    rating: 4.7,
    learners: "220+",
    language: "English",
    level: "Beginner",
    classes: 4,
    ageRange: "6-10 yrs",
    timeSlot: "Late Evening",
    originalPrice: 379,
    salePrice: 219,
    badge: "New",
    teacher: { name: "Andy Brew", subject: "Maths", rating: 4.8 },
    syllabus: ["Patterns", "Puzzles", "Speed math", "Challenge day"],
  },
  {
    id: "spoken-english-essentials",
    image: courseSpeaking,
    title: "Spoken English essentials: speak clearly and confidently",
    description: "Daily speaking drills and activity-based confidence sessions.",
    rating: 4.8,
    learners: "300+",
    language: "English",
    level: "All Levels",
    classes: 5,
    ageRange: "7-12 yrs",
    timeSlot: "Evening",
    originalPrice: 459,
    salePrice: 269,
    badge: "Selling Fast",
    teacher: { name: "Andy Brew", subject: "Communication", rating: 4.9 },
    syllabus: ["Pronunciation", "Vocabulary", "Conversation", "Story talk", "Final showcase"],
  },
  {
    id: "microbit-stem-lab",
    image: courseRobotics,
    title: "Micro:bit STEM lab: coding sensors, lights and mini robots",
    description: "Hands-on projects with block coding and simple hardware modules.",
    rating: 4.9,
    learners: "175+",
    language: "English",
    level: "Intermediate",
    classes: 6,
    ageRange: "8-13 yrs",
    timeSlot: "Morning",
    originalPrice: 599,
    salePrice: 349,
    teacher: { name: "Andy Brew", subject: "STEM", rating: 4.9 },
    syllabus: ["Micro:bit intro", "LED matrix", "Sensors", "Radio", "Robot controls", "Final build"],
  },
];
